### ISSUE TITLE
Error with database

### ISSUE THREAD

**Issue by dedhill** [detectivekaktus/bridgewatcher#5]
After i build and run docker container i have this error

```
Traceback (most recent call last):
  File "/bridgewatcher/bot.py", line 6, in <module>
    from src.client import bot, DATABASE
  File "/bridgewatcher/src/client.py", line 38, in <module>
    SERVERS: Final[Servers] = Servers("servers/servers.db")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bridgewatcher/src/config/__init__.py", line 11, in __init__
    self.create_table()
  File "/bridgewatcher/src/config/__init__.py", line 25, in create_table
    with self as servers:
  File "/bridgewatcher/src/config/__init__.py", line 15, in __enter__
    self.connection = connect(self.path)
                      ^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

**Comment by detectivekaktus** [comment]
This commit should solve the problem. [fb4e94d](https://github.com/detectivekaktus/bridgewatcher/commit/fb4e94df022560660721ed2d9e4204c8da795ff6) (Use `git pull origin master` to update to the latest commit).

If it doesn't I'll continue investigating.
